import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster, toast } from 'sonner'
import { SessionProvider } from "next-auth/react"
import { QueryClientContext } from "@/providers/queryclient";
import Header from "@/components/template/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SessionProvider> */}
          <QueryClientContext>
            <Toaster duration={3000}/>
            {children}
          </QueryClientContext>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
